sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 7.6.0

before_install:
  - sudo apt-get update
  - sudo apt-get install wget python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev libc6-dev -y

install:
  - npm install

script:
  - npm test -- --coverage



after_success:
  - FULL_GCR_KEY="-----BEGIN PRIVATE KEY-----\n"$GCR_KEY"\n-----END PRIVATE KEY-----\n"
  - sed -i -e "s%\PWD%$FULL_GCR_KEY%g" gcregistry.json
  - docker login -u _json_key -p "$(cat gcregistry.json)" https://gcr.io
  - rm -rf gcregistry.json
  - |
    if [ "$TRAVIS_TAG" == "" ]; then
      IMAGE_TAG_NAME="latest"
    elif [ "$TRAVIS_TAG" != "" ]; then
      IMAGE_TAG_NAME="develop"
    fi;
  - docker build --quiet -t gcr.io/deep-wares-144610/middleware-eth:$IMAGE_TAG_NAME .
  - docker push gcr.io/deep-wares-144610/middleware-eth:$IMAGE_TAG_NAME




notifications:
  email: false

cache:
  directories:
    - node_modules