sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 6.10.3

services: mongodb


install:
  - npm install
  - export PATH=$PATH:$(pwd)/node_modules/.bin
  - export NODE_ENV=''
  - npm run prepare_linux_install


script:
  - testrpc > /dev/null &
  - nohup node . &
  - npm test -- --coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email: false

cache:
  directories:
    - node_modules