sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 6.10.3

services: mongodb


install:
  - npm install
  - export PATH=$PATH:$(pwd)/node_modules/.bin
  - export NODE_ENV=''
  - npm run prepare_linux_install


script:
  - npm run testrpc > /dev/null &
  - node . > /dev/null &
  - npm test -- --coverage

notifications:
  email: false

cache:
  directories:
    - node_modules