sudo: required
dist: trusty
os: linux
group: stable
language: node_js
node_js: 6.10.3

services: mongodb


install:
  - npm install

script:
  - npm run testrpc > /dev/null &
  - sleep 5 && npm run prepare_linux_install
  - sleep 5 && node . > /dev/null &
  - sleep 20 && npm test -- --coverage

notifications:
  email: false

cache:
  directories:
    - node_modules